import { describe,it,expect } from 'vitest';
import { readFileSync } from 'node:fs';
import PizZip from 'pizzip';
import { validStudy,cases } from './fixtures';
import { reviewStudy } from '../src/lib/reviewRules';
import { buildDocx,documentBody,filename } from '../src/lib/generateDocx';
import { optionalPermissions,pisSections } from '../src/data/documentText';
import { COURSES } from '../src/data/courses';
import { FELLOWS } from '../src/data/fellows';
const base=readFileSync('public/document-base.docx');
const banned=new RegExp('re'+'search','i');
describe('deterministic checks',()=>{
 it('accepts a valid simple interview',()=>expect(reviewStudy(validStudy())).toEqual([]));
 it('rejects empty purpose',()=>{const s=validStudy();s.purpose='';expect(reviewStudy(s).some(i=>i.id==='purpose-short'&&i.severity==='error')).toBe(true);});
 it('rejects placeholders',()=>{const s=validStudy();s.purpose='Fill in the purpose of the study in this space.';expect(reviewStudy(s).some(i=>i.id==='purpose-placeholder')).toBe(true);});
 it('warns when audio is not described',()=>{const s=validStudy();s.permissions.audio=true;expect(reviewStudy(s).some(i=>i.id==='recording-audio'&&i.severity==='warning')).toBe(true);expect(()=>buildDocx(s,base)).not.toThrow();});
 it('warns for interview selection with survey-only prose',()=>{const s=validStudy();s.activity='Participants complete a survey about local community spaces.';expect(reviewStudy(s).some(i=>i.id==='method-Individual interview')).toBe(true);});
 for(const key of ['distress','deception','capacity','pressure'] as const)it(`flags ${key} without blocking generation`,()=>{const s=validStudy();s.safeguards[key]=true;expect(reviewStudy(s).some(i=>i.id===`safeguard-${key}`&&i.severity==='fellow-review')).toBe(true);expect(()=>buildDocx(s,base)).not.toThrow();});
 it('does not claim low risk when distress is selected',()=>{const s=validStudy();s.safeguards.distress=true;expect(pisSections(s)[9].paragraphs[0]).not.toContain('No significant risks');});
 it('includes only separately selected optional consent clauses',()=>{const s=validStudy();expect(optionalPermissions(s)).toEqual([]);s.permissions.audio=true;s.permissions.identity=true;expect(optionalPermissions(s).map(p=>p.key)).toEqual(['audio','identity']);});
 it('does not promise anonymous quotations when identification is possible',()=>{const s=cases().D;expect(optionalPermissions(s).find(p=>p.key==='quotes')!.text).toContain('unless I separately agree');});
 it('retains all nine exact course names',()=>expect(COURSES).toEqual(['Tembusu Undergraduate Research Opportunity','Independent Study','The Tembusu Senior Learning Experience Project','Health and the Community in Singapore',"Singapore as 'Model' City?",'Happiness By Design','Picturing and Seeing Development','Technologies and Ageing in Singapore','Migrant Workers, Rhetoric, and Performance']));
 it('maps all ten fellows and rejects mismatched email',()=>{expect(FELLOWS).toHaveLength(10);for(const f of FELLOWS){const s={...validStudy(),fellowName:f.name,fellowEmail:f.email};expect(reviewStudy(s)).toEqual([]);expect(documentBody(s)).toContain(f.email);}const s=validStudy();s.fellowEmail='wrong@nus.edu.sg';expect(reviewStudy(s).some(i=>i.field==='fellowName')).toBe(true);});
 it('rejects invalid age bounds, zero duration, missing method and missing other text',()=>{const s=validStudy();s.maxAge='18';s.duration='0';s.methods=['Other'];expect(reviewStudy(s).filter(i=>i.severity==='error').map(i=>i.field)).toEqual(expect.arrayContaining(['maxAge','duration','otherMethod']));});
 it('supports decimal duration and no upper age limit',()=>{const s=validStudy();s.duration='1.5';s.unit='hours';s.noUpperAge=true;s.maxAge='';expect(reviewStudy(s)).toEqual([]);expect(documentBody(s)).toContain('1.5 hours');});
 it('warns for long duration without blocking',()=>{const s=validStudy();s.duration='481';expect(reviewStudy(s).some(i=>i.id==='duration-long')).toBe(true);expect(()=>buildDocx(s,base)).not.toThrow();});
 it('blocks terminology outside the course-name exception',()=>{const s=validStudy();s.purpose+=' This is a '+'re'+'search study.';expect(reviewStudy(s).some(i=>i.id==='terminology-purpose')).toBe(true);});
 it('escapes XML and creates a safe filename',()=>{const s=validStudy();s.title='Community <connections> & shared spaces';expect(documentBody(s)).toContain('&lt;connections&gt; &amp;');expect(filename(s)).not.toMatch(/[<>]/);});
 it('blocks generation with errors',()=>{const s=validStudy();s.purpose='';expect(()=>buildDocx(s,base)).toThrow();});
 for(const [name,s] of Object.entries(cases()))it(`generates clean editable DOCX for case ${name}`,()=>{const zip=new PizZip(buildDocx(s,base));const text=Object.keys(zip.files).filter(n=>n.endsWith('.xml')).map(n=>zip.file(n)!.asText()).join(' ');expect(banned.test(text)).toBe(false);expect(text).not.toMatch(/undefined|\{\{|w:highlight/);expect(zip.file('word/document.xml')!.asText()).toContain('<w:pageBreakBefore/>');expect(zip.file('word/footer1.xml')!.asText()).toContain('NUMPAGES');expect(zip.file('word/header1.xml')!.asText()).toEqual(new PizZip(base).file('word/header1.xml')!.asText());});
 it('allows the official course-name exception and no other occurrences',()=>{const s=validStudy();s.course=COURSES[0];const text=documentBody(s);expect(banned.test(text.replaceAll(COURSES[0],''))).toBe(false);expect(text.split(COURSES[0])).toHaveLength(3);});
});
