import {chromium} from '@playwright/test';
import {spawn} from 'node:child_process';
import {mkdirSync,readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import PizZip from 'pizzip';
mkdirSync('qa',{recursive:true});
const server=spawn('npm',['run','preview','--','--port','4173'],{stdio:'inherit'});
for(let i=0;i<40;i++){try{if((await fetch('http://127.0.0.1:4173')).ok)break;}catch{}await new Promise(r=>setTimeout(r,250));}
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:1366,height:900},acceptDownloads:true});
 const requests=[]; const failures=[];
 page.on('request',r=>requests.push({url:r.url(),method:r.method(),data:r.postData()}));
 page.on('pageerror',e=>failures.push(e.message));
 await page.goto('http://127.0.0.1:4173');
 await page.screenshot({path:'qa/desktop.png',fullPage:true});
 await page.getByLabel('Study title',{exact:true}).fill('Understanding Neighbourhood Belonging in Singapore');
 await page.getByLabel('Course',{exact:true}).selectOption('Health and the Community in Singapore');
 await page.getByLabel('Principal Investigator',{exact:true}).selectOption('Connor Graham');
 await page.getByLabel('Full name',{exact:true}).fill('Alex Tan');
 await page.getByLabel('NUS email address',{exact:true}).fill('alex.tan@u.nus.edu');
 await page.getByLabel('Approximate number of participants').fill('20');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByLabel('What is the purpose of this study?',{exact:true}).fill('Explore belonging.');
 await page.getByLabel('What will participants be asked to do?',{exact:true}).fill('Participants will take part in an individual interview about everyday neighbourhood experiences and community connections.');
 await page.getByLabel('Individual interview',{exact:true}).check();
 await page.getByLabel('Approximately how long will each participant be involved?',{exact:true}).fill('30');
 await page.getByLabel('Maximum participant age',{exact:true}).fill('65');
 assert.equal(await page.getByRole('spinbutton',{name:'Minimum participant age',exact:true}).count(),0);
 assert.equal(await page.getByRole('heading',{name:'Data & coursework use'}).count(),0);
 await page.getByLabel('Exclusion criteria (optional)',{exact:true}).fill('People who have already completed this activity.');
 await page.getByRole('group',{name:'Will participants be audio recorded?',exact:true}).getByLabel('Yes',{exact:true}).check();
 await page.getByRole('button',{name:'Check study →',exact:true}).click();
 await page.getByRole('button',{name:'Return to section',exact:true}).click();
 await page.waitForFunction(()=>document.activeElement?.getAttribute('data-field')==='purpose');
 await page.getByRole('button',{name:'Check study →',exact:true}).click();
 await page.getByRole('button',{name:'Dismiss',exact:true}).click();
 assert.equal(await page.getByRole('heading',{name:'Please review',exact:true}).count(),0);
 await page.getByRole('button',{name:'← Back and edit',exact:true}).click();
 await page.getByLabel('What will participants be asked to do?',{exact:true}).fill('Participants will take part in an individual interview about everyday neighbourhood experiences and local connections.');
 await page.getByRole('button',{name:'Check study →',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'Dismiss',exact:true}).count(),1);
 await page.getByRole('button',{name:'Dismiss',exact:true}).click();
 assert(await page.getByText('No blocking issues detected',{exact:true}).isVisible());
 await page.getByRole('button',{name:'Generate Word document',exact:true}).click();
 await page.getByRole('button',{name:'↓ Download Word document',exact:true}).waitFor();
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'↓ Download Word document',exact:true}).click();
 const download=await downloadPromise;await download.saveAs('qa/browser-download.docx');
 assert(download.suggestedFilename().startsWith('Tembusu_PIS_CF_'));
 const xml=new PizZip(readFileSync('qa/browser-download.docx')).file('word/document.xml').asText();
 assert(xml.includes('rctccg@nus.edu.sg'));assert(xml.includes('Exclusion criteria:'));assert(xml.includes('18 for NUS students, 21 for non-NUS students'));assert(xml.includes('INFORMED CONSENT FORM'));
 assert.equal(requests.some(r=>r.data||r.method!=='GET'||!r.url.startsWith('http://127.0.0.1:4173/')),false);
 assert.equal(requests.some(r=>r.url.includes('Alex')||r.url.includes('Belonging')),false);
 assert.deepEqual(failures,[]);
 assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);
 assert.equal((await page.context().cookies()).length,0);
 await page.screenshot({path:'qa/download.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.reload();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'qa/mobile.png',fullPage:true});
 console.log('Browser flow, actual download, fixed Fellow email, mobile overflow, no form-data requests, no storage/cookies and no JS errors: PASS');
}finally{await browser.close();server.kill();}
