import { useEffect, useRef, useState } from 'react';
import type { Study } from './types/study';
import { emptyStudy } from './types/study';
import { COURSES } from './data/courses';
import { FELLOWS } from './data/fellows';
import { METHODS, PERMISSIONS, SAFEGUARDS } from './data/questions';
import { MINIMUM_AGE_NOTICE, PRIVACY_NOTICE, REVIEW_NOTICE, REVIEW_CONFIRMATION, durationText } from './data/documentText';
import { validateDetails, type FieldErrors } from './lib/validation';
import { reviewStudy } from './lib/reviewRules';
import { filename, generateDocx } from './lib/generateDocx';
import { Field, YesNo } from './components/Fields';
const STEPS=['Study details','Participant activity','Check','Download'];
export default function App(){
 const [study,setStudy]=useState<Study>(emptyStudy);
 const [step,setStep]=useState(0);const [errors,setErrors]=useState<FieldErrors>({});
 const [busy,setBusy]=useState(false);const [generationError,setGenerationError]=useState('');
 const [file,setFile]=useState<Blob|null>(null);const [resetOpen,setResetOpen]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null);
 const pendingField=useRef<string|null>(null);
 const [dismissed,setDismissed]=useState<string[]>([]);
 const issues=reviewStudy(study).filter(i=>i.severity!=='warning'||!dismissed.includes(i.id));const blocking=issues.filter(i=>i.severity==='error');const warnings=issues.filter(i=>i.severity==='warning');const flags=issues.filter(i=>i.severity==='fellow-review');
 useEffect(()=>{if(pendingField.current){const key=pendingField.current;pendingField.current=null;requestAnimationFrame(()=>{const target=document.querySelector<HTMLElement>(`[data-field="${key}"]`);if(target){target.scrollIntoView({block:'center'});(target.matches('input,textarea,select')?target:target.querySelector<HTMLElement>('input,textarea,select'))?.focus({preventScroll:true});}else heading.current?.focus();});}else if(step>0)heading.current?.focus();},[step]);
 useEffect(()=>setDismissed([]),[study]);
 function update<K extends keyof Study>(key:K,value:Study[K]){setStudy(s=>({...s,[key]:value}));setFile(null);setErrors(e=>({...e,[key]:''}));}
 function go(n:number){setStep(n);setErrors({});window.scrollTo({top:0,behavior:'instant'});}
 function next(){if(step===0){const e=validateDetails(study);setErrors(e);if(Object.keys(e).length){setTimeout(()=>document.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus(),0);return;}}go(step+1);}
 async function generate(){if(blocking.length)return;setBusy(true);setGenerationError('');try{setFile(await generateDocx(study));go(3);}catch(e){setGenerationError(e instanceof Error?e.message:'Unable to generate the document. Please try again.');}finally{setBusy(false);}}
 function download(){if(!file)return;const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=filename(study);a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function input(key:keyof Study,label:string,opts:{hint?:string;type?:string;maxLength?:number;min?:number;step?:string}={}){
 return <Field label={label} error={errors[key]} hint={opts.hint}>{(id,desc)=><input data-field={key} id={id} type={opts.type||'text'} value={String(study[key])} onChange={e=>update(key,e.target.value as never)} maxLength={opts.maxLength} min={opts.min} step={opts.step} aria-invalid={!!errors[key]} aria-describedby={desc}/>}</Field>;
 }
 function textArea(key:'purpose'|'activity',label:string,prompt:string,range:string){return <Field label={label} error={errors[key]} hint={prompt}>{(id,desc)=><><textarea data-field={key} id={id} value={study[key]} rows={5} onChange={e=>update(key,e.target.value)} aria-describedby={`${desc} ${id}-count`} aria-invalid={!!errors[key]}/><div className="counter" id={`${id}-count`}>Recommended: {range} characters <span>{study[key].length} characters</span></div></>}</Field>;}
 function editIssue(field:string){pendingField.current=field;const detail=['title','course','fellowName','fellowEmail','students','partner','count'];go(detail.includes(field)||field.startsWith('student')?0:1);}
 return <><a className="skip" href="#main">Skip to form</a><header className="site-header"><div className="header-inner"><img src={`${import.meta.env.BASE_URL}tembusu-nus.png`} alt="Tembusu College, National University of Singapore"/></div></header>
 <main id="main" className="shell"><div className="intro"><h1>Participant information &amp; consent</h1></div>
 <nav className="progress" aria-label="Form progress"><ol>{STEPS.map((s,i)=><li key={s} className={i===step?'active':i<step?'complete':''} aria-current={i===step?'step':undefined}><button type="button" disabled={i>step||i===3} onClick={()=>go(i)}><span className="step-number">{i<step?'✓':i+1}</span><span>{s}</span></button></li>)}</ol></nav>
 <div className="layout"><section className="form-panel"><div className="section-intro"><p className="eyebrow">STEP {step+1} OF 4</p><h2 ref={heading} tabIndex={-1}>{step===3?'Your documents are ready':STEPS[step]}</h2><p>{step===0?'Tell us about your study and the people responsible for it. All fields are required unless marked optional.':step===1?'Use clear, everyday language so participants can make an informed choice.':step===2?'Check the details and address any issues before generating your document.':'Your Participant Information Sheet and Consent Form are ready.'}</p></div>
 {step===0&&<form noValidate onSubmit={e=>{e.preventDefault();next();}}>
 {Object.values(errors).some(Boolean)&&<div className="notice error" role="alert">Please correct the highlighted fields below.</div>}
 {input('title','Study title',{hint:'Use a formal, descriptive title.',maxLength:180})}
 <Field label="Course" error={errors.course}>{(id,desc)=><select data-field="course" id={id} value={study.course} onChange={e=>update('course',e.target.value)} aria-invalid={!!errors.course} aria-describedby={desc}><option value="">Select your course</option>{COURSES.map(c=><option key={c}>{c}</option>)}</select>}</Field>
 <Field label="Principal Investigator" error={errors.fellowName} hint="The selected Principal Investigator’s email will be added automatically to your document.">{(id,desc)=><select data-field="fellowName" id={id} value={study.fellowName} aria-invalid={!!errors.fellowName} aria-describedby={desc} onChange={e=>{const fellow=FELLOWS.find(f=>f.name===e.target.value);setStudy(s=>({...s,fellowName:fellow?.name||'',fellowEmail:fellow?.email||''}));setErrors(e=>({...e,fellowName:'',fellowEmail:''}));setFile(null);}}><option value="">Select your Principal Investigator</option>{FELLOWS.map(f=><option key={f.name} value={f.name}>{f.name}</option>)}</select>}</Field>
 <div className="subsection"><h3>Student investigators</h3><p className="hint">Include between 1 and 8 students.</p>{study.students.map((p,i)=><fieldset className="student" key={i}><legend>Student {i+1}</legend><div className="two-columns">{(['name','email'] as const).map(k=><Field key={k} label={k==='name'?'Full name':'NUS email address'} error={errors[`student${k==='name'?'Name':'Email'}${i}`]}>{(id,desc)=><input data-field={`student${k==='name'?'Name':'Email'}${i}`} id={id} type={k==='email'?'email':'text'} value={p[k]} aria-invalid={!!errors[`student${k==='name'?'Name':'Email'}${i}`]} aria-describedby={desc} onChange={e=>{update('students',study.students.map((v,j)=>j===i?{...v,[k]:e.target.value}:v));setErrors(old=>({...old,[`student${k==='name'?'Name':'Email'}${i}`]:''}));}}/>}</Field>)}</div>{study.students.length>1&&<button type="button" className="text-button remove" onClick={()=>update('students',study.students.filter((_,j)=>j!==i))} aria-label={`Remove student ${i+1}`}>Remove</button>}</fieldset>)}{study.students.length<8&&<button type="button" className="text-button" onClick={()=>update('students',[...study.students,{name:'',email:''}])}>＋ Add student</button>}</div>
 {input('partner','Community partner or external organisation, if applicable',{hint:'Optional. Leave blank if there is no community partner.'})}
 <div className="half-width">{input('count','Approximate number of participants',{type:'number',min:1,step:'1'})}</div>
 <div className="actions"><span className="hint">Next: Participant activity</span><button type="submit" className="primary">Continue <span aria-hidden="true">→</span></button></div>
 </form>}
 {step===1&&<form noValidate onSubmit={e=>{e.preventDefault();next();}}>
 <section className="activity-section">{textArea('purpose','What is the purpose of this study?','Briefly explain, in language understandable to a member of the public, what the study aims to understand, explore or accomplish.','50–800')}{textArea('activity','What will participants be asked to do?','Describe exactly what participation involves. For example, explain whether participants will answer questions, complete a survey, take part in an interview, join a discussion or participate in an activity.','50–1,200')}</section>
 <fieldset data-field="methods" className="activity-section methods"><legend>How will participants take part?</legend><div className="method-grid">{METHODS.map(m=><label key={m}><input type="checkbox" checked={study.methods.includes(m)} onChange={e=>update('methods',e.target.checked?[...study.methods,m]:study.methods.filter(v=>v!==m))}/>{m}</label>)}</div>{study.methods.includes('Other')&&input('otherMethod','Please specify')}</fieldset>
 <section className="activity-section"><h3>Duration &amp; eligibility</h3><div className="two-columns">{input('duration','Approximately how long will each participant be involved?',{type:'number',min:0,step:'any'})}<Field label="Duration unit">{id=><select id={id} value={study.unit} onChange={e=>update('unit',e.target.value as Study['unit'])}><option value="minutes">minutes</option><option value="hours">hours</option></select>}</Field></div><div className="age-note"><strong>Minimum participant age</strong><p>{MINIMUM_AGE_NOTICE}</p></div>{!study.noUpperAge&&input('maxAge','Maximum participant age',{type:'number',min:18,step:'1'})}<label className="check-line"><input type="checkbox" checked={study.noUpperAge} onChange={e=>update('noUpperAge',e.target.checked)}/>No specific upper age limit</label><YesNo label="Is there any other eligibility requirement?" value={study.hasEligibility} onChange={v=>update('hasEligibility',v)}/>{study.hasEligibility&&input('eligibility','Briefly describe who is eligible.')}{input('exclusion','Exclusion criteria (optional)',{hint:'Leave blank if there are no additional exclusion criteria.'})}</section>
 <section className="activity-section"><h3>Recording &amp; participant material</h3><p>Each “Yes” adds a separate consent choice to the document.</p>{PERMISSIONS.map(p=><YesNo key={p.key} label={p.label} value={study.permissions[p.key]} onChange={v=>update('permissions',{...study.permissions,[p.key]:v})}/>)}</section>
 <section className="activity-section"><h3>Ethics safeguards</h3><p>These answers are used for the study check. The questions themselves will not be printed in the document.</p>{SAFEGUARDS.map(q=><YesNo key={q.key} label={q.label} value={study.safeguards[q.key]} onChange={v=>update('safeguards',{...study.safeguards,[q.key]:v})}/>)}</section>
 <div className="actions"><button type="button" className="secondary" onClick={()=>go(0)}>← Back</button><button className="primary" type="submit">Check study →</button></div></form>}
 {step===2&&<><div className="summary"><h3>Study summary</h3><dl>{[['Study',study.title],['Course',study.course],['Principal Investigator',study.fellowName],['Student investigators',String(study.students.length)],['Participant method',study.methods.map(m=>m==='Other'?`Other: ${study.otherMethod}`:m).join(', ')||'Not selected'],['Duration',study.duration?durationText(study):'Not entered'],['Number of participants',study.count||'Not entered'],['Recording & quotations',PERMISSIONS.filter(p=>study.permissions[p.key]).map(p=>p.short).join(', ')||'None']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div>
 <h3 className="check-heading">Study check</h3><p className="hint">These checks use fixed validation and keyword rules. They do not assess the meaning of your prose or provide formal ethics approval.</p>
 {!blocking.length&&<div className="notice success"><strong>No blocking issues detected</strong><p>Check the wording and details carefully before sharing the document.</p></div>}
 {(['error','warning','fellow-review'] as const).map(severity=>{const list=issues.filter(i=>i.severity===severity);return list.length>0&&<div className={`notice ${severity}`} key={severity}><h4>{severity==='error'?'Changes required':severity==='warning'?'Please review':'Principal Investigator review required'}</h4>{severity==='fellow-review'&&<p>{REVIEW_NOTICE}</p>}<ul>{list.map(i=><li key={i.id}><p>{i.message}</p>{i.suggestion&&<p>{i.suggestion}</p>}{severity!=='fellow-review'&&<div className="issue-actions"><button className="text-button" onClick={()=>editIssue(i.field)}>Return to section</button>{severity==='warning'&&<button className="text-button" onClick={()=>setDismissed(d=>[...d,i.id])}>Dismiss</button>}</div>}</li>)}</ul>{severity==='fellow-review'&&<p><strong>{REVIEW_CONFIRMATION}</strong></p>}</div>})}
 {warnings.length>0&&<p className="hint">You may continue with warnings after checking them. Generating the document confirms that you have reviewed the notices above.</p>}
 {generationError&&<p role="alert" className="notice error">{generationError}</p>}
 <div className="actions"><button className="secondary" onClick={()=>go(1)}>← Back and edit</button><button className="primary" disabled={blocking.length>0||busy} onClick={generate}>{busy?'Preparing document…':'Generate Word document'} <span aria-hidden="true">→</span></button></div></>}
 {step===3&&<><div className="download-result"><div className="document-icon" aria-hidden="true">W</div><div><h3>Participant Information Sheet<br/>&amp; Consent Form</h3><p>Editable Microsoft Word document · .docx</p><p className="file-name">{filename(study)}</p></div></div>{flags.length>0&&<div className="notice fellow-review"><h4>Principal Investigator review required</h4><p>{REVIEW_CONFIRMATION}</p></div>}<button className="primary download" onClick={download}>↓ Download Word document</button><p className="hint">Review the Word document before sharing it with participants.</p><div className="actions"><button className="secondary" onClick={()=>go(2)}>← Back to check</button><button className="text-button" onClick={()=>setResetOpen(true)}>Start a new study</button></div>{resetOpen&&<div className="notice warning" role="alert"><h4>Clear this study?</h4><p>Your entries will be removed from this page. Download your document first if you need a copy.</p><div className="reset-actions"><button className="secondary" onClick={()=>setResetOpen(false)}>Keep this study</button><button className="primary" onClick={()=>{setStudy(emptyStudy());setFile(null);setResetOpen(false);go(0);}}>Clear and start again</button></div></div>}</>}
 </section><aside><h3>{step===0?'Before you begin':step===3?'Before you share':'A clear, informed choice'}</h3>{step===0?<ol className="guidance"><li>Have your study details and student team contacts ready.</li><li>Explain what participants will do in your own words.</li><li>Check the details, then download both forms in one Word document.</li></ol>:<p>{step===3?'Read the complete document and arrange any required Principal Investigator review before participant recruitment.':'Give participants the information they need to decide whether to take part. Describe the activity, duration and any recording clearly.'}</p>}<div className="privacy"><span aria-hidden="true">◇</span><h4>Your information stays here</h4><p>{PRIVACY_NOTICE}</p><p>Refreshing or closing this page clears your entries.</p></div><p className="scope">For Tembusu College coursework studies. This tool does not provide formal ethics approval.</p></aside></div>
</main></>;
}
